#! /bin/sh
# /etc/init.d/automount

case "$1" in
  start)
    echo "Mounting HDD..."
    # run application you want to start
    sudo mount /dev/sda1 /home/pi/FTP
    ;;
  stop)
    echo "Unmounting HDD..."
    # kill application you want to stop
    sudo umount /dev/sd1
    ;;
  *)
    echo "Usage: /etc/init.d/automount {start|stop}"
    exit 1
    ;;
esac

